apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rees
  namespace: flux-system  # Flux system manages kustomizations
spec:
  interval: 1m0s
  path: ./clusters/my-cluster/deploy  # Ensure this exists
  prune: true
  sourceRef:
    kind: GitRepository
    name: rees  # Ensure this matches the GitRepository name
  targetNamespace: my-app  # Ensures resources deploy into 'my-app'