apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app
spec:
  selector:
    app: my-app  # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80    # The port you want to expose
      targetPort: 8080  # This should match the container's port
  type: NodePort  # Change to NodePort or LoadBalancer if needed